baseURL: "https://xuanliu7.github.io"  
title: Xuan Liu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        - name: CV
          url: cv_xuanliu.pdf
          weight: 4 


params:
    description: "This website hosts Xuan Liu's research papers, curriculum vitae, and contact information."
    author: Xuan Liu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","publications"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Xuan Liu
          subtitle: "I am a Postdoctoral Scholar at the [Scripps Institution of Oceanography](https://scripps.ucsd.edu/), University of California San Diego, working with Prof. Amato Evan. I am an atmospheric scientist studying mineral dust — how it is measured, modeled, and how it affects air quality, human health, and climate. My work combines field observations, elemental and mineralogical analysis, satellite remote sensing, and atmospheric modeling (WRF-Chem) to reduce uncertainty in how dust concentration, composition, and emissions are represented, from instruments to atmospheric models."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: aboutme/
            - name: Research
              url: research/
            - name: Publications
              url: publications/
            - name: CV
              url: cv_xuanliu.pdf

    socialIcons:
        - name: Email
          url: mailto:xul047@ucsd.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=hbZUHxkAAAAJ&view_op=list_works&sortby=pubdate


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xuan Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2